"""Cheap document filters. Data quality moves model quality more than any model tweak.

These are simple rules, not a full cleaning pipeline. FineWeb-Edu is already
filtered and deduplicated by Hugging Face; the code rules follow the ones used
for the Codex / StarCoder training sets.
"""

import hashlib
import re

PERMISSIVE_LICENSES = {"mit", "apache-2.0", "bsd-2-clause", "bsd-3-clause", "isc", "unlicense", "cc0-1.0"}

_AUTOGEN = re.compile(r"auto-?generated|do not edit|generated by", re.IGNORECASE)


def keep_text(text: str, min_chars: int = 200, max_chars: int = 200_000) -> bool:
    return min_chars <= len(text) <= max_chars


def keep_code(text: str, min_chars: int = 100, max_chars: int = 200_000) -> bool:
    if not (min_chars <= len(text) <= max_chars):
        return False
    lines = text.splitlines() or [""]
    if max(len(line) for line in lines) > 1000:  # minified code or embedded data
        return False
    if sum(len(line) for line in lines) / len(lines) > 100:
        return False
    alnum = sum(ch.isalnum() for ch in text) / len(text)
    if alnum < 0.25:  # mostly symbols: data blobs, base64, tables
        return False
    if _AUTOGEN.search(text[:1000]):
        return False
    return True


class Deduplicator:
    """Drops exact duplicates (after trimming whitespace). Keeps 8 bytes per document."""

    def __init__(self):
        self._seen: set[bytes] = set()

    def is_new(self, text: str) -> bool:
        digest = hashlib.blake2b(text.strip().encode("utf-8", "ignore"), digest_size=8).digest()
        if digest in self._seen:
            return False
        self._seen.add(digest)
        return True


def goes_to_val(text: str, val_permille: int) -> bool:
    """Deterministic train/val split by content hash, so a document never lands in both."""
    digest = hashlib.blake2b(text.encode("utf-8", "ignore"), digest_size=4).digest()
    return int.from_bytes(digest, "little") % 1000 < val_permille
